### ISSUE TITLE
https://www.slf4j.org is inaccessible because SSL Certificates on slf4j.org has expired on September 17, 2023 at 7:42:00 AM

### ISSUE THREAD

**Issue by vorburger** [qos-ch/slf4j-site#9]
@ceki FYI https://www.slf4j.org is inaccessible because SSL Certificates on slf4j.org has expired on September 17, 2023 at 7:42:00 AM

Renew?

**Comment by ceki** [comment]
@vorburger  Thank you for the heads up. Problem should be solved now. 

BTW, I wrote test a case to prevent this from happening in the future.

**Comment by JnRouvignac** [comment]
I think you can now close this issue :)
